# Generated by Django 4.2.10 on 2024-03-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_liczby'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='suma',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
